name: genie101
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.6.6
  salomon_bottom_bar: ^3.3.2
  google_fonts: ^6.2.1
  device_preview: ^1.2.0
  material_symbols_icons: ^4.2785.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/



